
using Microsoft.EntityFrameworkCore;
using Anketa.Domain.Entities;
using Anketa.Domain.Enums;

namespace Anketa.DataAccess.Extensions
{
    public static class DataSeedExtensions
    {
        public static void SeedData(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Role>().HasData(
                new Role { Id = 1, Name = "Admin", Description = "Full system access", Type = RoleType.Admin },
                new Role { Id = 2, Name = "Employee", Description = "Can answer questions and view own responses", Type = RoleType.Employee },
                new Role { Id = 3, Name = "MCViewAll", Description = "Can view all reports across organization", Type = RoleType.MCViewAll },
                new Role { Id = 4, Name = "SectorManager", Description = "Can view all data within assigned sector", Type = RoleType.SectorManager },
                new Role { Id = 5, Name = "DepartmentManager", Description = "Can view all data within assigned department", Type = RoleType.DepartmentManager },
                new Role { Id = 6, Name = "LineManager", Description = "Can view data within assigned line/team", Type = RoleType.LineManager }
            );
            modelBuilder.Entity<QuestionType>().HasData(
                new QuestionType { Id = 1, Name = "Scale", Description = "1-10 Scale" },
                new QuestionType { Id = 2, Name = "Text", Description = "Text Answer" }
            );

            modelBuilder.Entity<User>().HasData(
    new User
    {
        Id = 1,
        CompanyId = 1064,
        Gender = Gender.Female,
        Sector = Sector.Finance,
        Department = "Financial Controlling and Reporting",
        Line = "Financial Controlling and Reporting",
        PositionType = PositionType.Exempt,
        Age = 57,
        WorkExperience = 26,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1064",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 2,
        CompanyId = 1179,
        Gender = Gender.Female,
        Sector = Sector.Finance,
        Department = "Accounting & Treasury",
        Line = "Accounting & Treasury",
        PositionType = PositionType.WhiteCollar,
        Age = 60,
        WorkExperience = 21,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1179",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 3,
        CompanyId = 1345,
        Gender = Gender.Female,
        Sector = Sector.Finance,
        Department = "Financial Controlling and Reporting",
        Line = "Financial Controlling and Reporting",
        PositionType = PositionType.Exempt,
        Age = 36,
        WorkExperience = 3,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1345",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 4,
        CompanyId = 1354,
        Gender = Gender.Female,
        Sector = Sector.Finance,
        Department = "Accounting & Treasury",
        Line = "Accounting & Treasury",
        PositionType = PositionType.WhiteCollar,
        Age = 51,
        WorkExperience = 2,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1354",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 5,
        CompanyId = 1377,
        Gender = Gender.Female,
        Sector = Sector.Finance,
        Department = "Accounting & Treasury",
        Line = "Accounting & Treasury",
        PositionType = PositionType.WhiteCollar,
        Age = 49,
        WorkExperience = 1,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1377",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 6,
        CompanyId = 1009,
        Gender = Gender.Male,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.BlueCollar,
        Age = 59,
        WorkExperience = 39,
        EducationLevel = EducationLevel.NK,
        RoleId = 2,
        Password = "1009",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 7,
        CompanyId = 1010,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Human Resources",
        Line = "Human Resources",
        PositionType = PositionType.WhiteCollar,
        Age = 59,
        WorkExperience = 39,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1010",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 8,
        CompanyId = 1048,
        Gender = Gender.Male,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.WhiteCollar,
        Age = 51,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1048",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
     new User
     {
         Id = 9,
         CompanyId = 1085,
         Gender = Gender.Female,
         Sector = Sector.HRandLA,
         Department = "Facility",
         Line = "Facility",
         PositionType = PositionType.BlueCollar,
         Age = 55,
         WorkExperience = 26,
         EducationLevel = EducationLevel.KV,
         RoleId = 2,
         Password = "1085",
         IsActive = true,
         CreatedDate = DateTime.UtcNow
     },
     new User
     {
         Id = 10,
         CompanyId = 1139,
         Gender = Gender.Male,
         Sector = Sector.HRandLA,
         Department = "Union",
         Line = "Union",
         PositionType = PositionType.BlueCollar,
         Age = 62,
         WorkExperience = 25,
         EducationLevel = EducationLevel.SSS,
         RoleId = 2,
         Password = "1139",
         IsActive = true,
         CreatedDate = DateTime.UtcNow
     },
     new User
     {
         Id = 11,
         CompanyId = 1160,
         Gender = Gender.Female,
         Sector = Sector.HRandLA,
         Department = "Facility",
         Line = "Facility",
         PositionType = PositionType.BlueCollar,
         Age = 61,
         WorkExperience = 25,
         EducationLevel = EducationLevel.KV,
         RoleId = 2,
         Password = "1160",
         IsActive = true,
         CreatedDate = DateTime.UtcNow
     },
    new User
    {
        Id = 12,
        CompanyId = 1184,
        Gender = Gender.Female,
        Sector = Sector.CEOoffice,
        Department = "CEO office",
        Line = "CEO office",
        PositionType = PositionType.Exempt,
        Age = 56,
        WorkExperience = 19,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1184",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 13,
        CompanyId = 1195,
        Gender = Gender.Male,
        Sector = Sector.HRandLA,
        Department = "Internal Control",
        Line = "Internal Control",
        PositionType = PositionType.Exempt,
        Age = 41,
        WorkExperience = 17,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1195",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 14,
        CompanyId = 1285,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.BlueCollar,
        Age = 53,
        WorkExperience = 5,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1285",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 15,
        CompanyId = 1356,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.WhiteCollar,
        Age = 29,
        WorkExperience = 2,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1356",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 16,
        CompanyId = 1371,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Human Resources",
        Line = "Human Resources",
        PositionType = PositionType.Exempt,
        Age = 44,
        WorkExperience = 1,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1371",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 17,
        CompanyId = 1391,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.BlueCollar,
        Age = 44,
        WorkExperience = 0,
        EducationLevel = EducationLevel.NK,
        RoleId = 2,
        Password = "1391",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 18,
        CompanyId = 1392,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.WhiteCollar,
        Age = 36,
        WorkExperience = 0,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1392",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 19,
        CompanyId = 1399,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Human Resources",
        Line = "Human Resources",
        PositionType = PositionType.Exempt,
        Age = 43,
        WorkExperience = 0,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1399",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 20,
        CompanyId = 1400,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.WhiteCollar,
        Age = 24,
        WorkExperience = 0,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1400",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 21,
        CompanyId = 1405,
        Gender = Gender.Female,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.WhiteCollar,
        Age = 51,
        WorkExperience = 0,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1405",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 22,
        CompanyId = 1407,
        Gender = Gender.Male,
        Sector = Sector.HRandLA,
        Department = "Facility",
        Line = "Facility",
        PositionType = PositionType.BlueCollar,
        Age = 62,
        WorkExperience = 0,
        EducationLevel = EducationLevel.NK,
        RoleId = 2,
        Password = "1407",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },

    
    new User
    {
        Id = 23,
        CompanyId = 1017,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.WhiteCollar,
        Age = 61,
        WorkExperience = 38,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1017",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 24,
        CompanyId = 1023,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 59,
        WorkExperience = 36,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1023",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 25,
        CompanyId = 1028,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Labaratory control",
        PositionType = PositionType.BlueCollar,
        Age = 61,
        WorkExperience = 27,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1028",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 26,
        CompanyId = 1030,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Chemical labaratory",
        PositionType = PositionType.BlueCollar,
        Age = 50,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1030",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 27,
        CompanyId = 1031,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 55,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1031",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 28,
        CompanyId = 1044,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.Exempt,
        Age = 48,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1044",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 29,
        CompanyId = 1046,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Programming",
        PositionType = PositionType.WhiteCollar,
        Age = 48,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1046",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 30,
        CompanyId = 1047,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Stores",
        Line = "Stores",
        PositionType = PositionType.Exempt,
        Age = 47,
        WorkExperience = 24,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1047",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 31,
        CompanyId = 1050,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Preparation",
        PositionType = PositionType.BlueCollar,
        Age = 52,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1050",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 32,
        CompanyId = 1053,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Labaratory control",
        PositionType = PositionType.BlueCollar,
        Age = 55,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1053",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 33,
        CompanyId = 1056,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Programming",
        PositionType = PositionType.WhiteCollar,
        Age = 48,
        WorkExperience = 27,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1056",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 34,
        CompanyId = 1063,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Customer service",
        PositionType = PositionType.WhiteCollar,
        Age = 52,
        WorkExperience = 26,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1063",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 35,
        CompanyId = 1068,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 59,
        WorkExperience = 27,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1068",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 36,
        CompanyId = 1072,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.Exempt,
        Age = 58,
        WorkExperience = 27,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1072",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 37,
        CompanyId = 1076,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Scrap management",
        PositionType = PositionType.BlueCollar,
        Age = 47,
        WorkExperience = 26,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1076",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 38,
        CompanyId = 1081,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 47,
        WorkExperience = 26,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1081",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 39,
        CompanyId = 1082,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 51,
        WorkExperience = 26,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1082",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 40,
        CompanyId = 1089,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Labaratory control",
        PositionType = PositionType.BlueCollar,
        Age = 48,
        WorkExperience = 26,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1089",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 41,
        CompanyId = 1100,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 52,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1100",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 42,
        CompanyId = 1101,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 58,
        WorkExperience = 25,
        EducationLevel = EducationLevel.VKV,
        RoleId = 2,
        Password = "1101",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    // ==================== SUPPLY CHAIN SECTOR CONTINUED ====================
    new User
    {
        Id = 43,
        CompanyId = 1118,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 48,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1118",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 44,
        CompanyId = 1125,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Preparation",
        PositionType = PositionType.BlueCollar,
        Age = 56,
        WorkExperience = 25,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1125",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 45,
        CompanyId = 1130,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 45,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1130",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 46,
        CompanyId = 1133,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 47,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1133",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 47,
        CompanyId = 1135,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Purchasing",
        Line = "Purchasing",
        PositionType = PositionType.Exempt,
        Age = 47,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1135",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 48,
        CompanyId = 1137,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 47,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1137",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 49,
        CompanyId = 1142,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 47,
        WorkExperience = 9,
        EducationLevel = EducationLevel.NK,
        RoleId = 2,
        Password = "1142",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 50,
        CompanyId = 1143,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 56,
        WorkExperience = 25,
        EducationLevel = EducationLevel.NK,
        RoleId = 2,
        Password = "1143",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 51,
        CompanyId = 1144,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 50,
        WorkExperience = 25,
        EducationLevel = EducationLevel.NK,
        RoleId = 2,
        Password = "1144",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 52,
        CompanyId = 1146,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 53,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1146",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 53,
        CompanyId = 1150,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 48,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1150",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 54,
        CompanyId = 1152,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 59,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1152",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 55,
        CompanyId = 1153,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Labaratory control",
        PositionType = PositionType.BlueCollar,
        Age = 57,
        WorkExperience = 25,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1153",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 56,
        CompanyId = 1155,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Stores",
        Line = "Stores",
        PositionType = PositionType.BlueCollar,
        Age = 52,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1155",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 57,
        CompanyId = 1156,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.Exempt,
        Age = 51,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1156",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 58,
        CompanyId = 1159,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 60,
        WorkExperience = 25,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1159",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 59,
        CompanyId = 1162,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Preparation",
        PositionType = PositionType.Exempt,
        Age = 52,
        WorkExperience = 24,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1162",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 60,
        CompanyId = 1177,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Logistics",
        PositionType = PositionType.Exempt,
        Age = 61,
        WorkExperience = 25,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1177",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 61,
        CompanyId = 1178,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Purchasing",
        Line = "Purchasing",
        PositionType = PositionType.Exempt,
        Age = 53,
        WorkExperience = 23,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1178",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 62,
        CompanyId = 1180,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Chemical labaratory",
        PositionType = PositionType.BlueCollar,
        Age = 59,
        WorkExperience = 22,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1180",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 63,
        CompanyId = 1186,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Purchasing",
        Line = "Purchasing",
        PositionType = PositionType.Exempt,
        Age = 53,
        WorkExperience = 18,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1186",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 64,
        CompanyId = 1188,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.Exempt,
        Age = 52,
        WorkExperience = 18,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1188",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 65,
        CompanyId = 1189,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Planning & Strategy",
        PositionType = PositionType.Exempt,
        Age = 49,
        WorkExperience = 18,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1189",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 66,
        CompanyId = 1190,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.Exempt,
        Age = 49,
        WorkExperience = 18,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1190",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 67,
        CompanyId = 1196,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Programming",
        PositionType = PositionType.Exempt,
        Age = 43,
        WorkExperience = 17,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1196",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 68,
        CompanyId = 1209,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 34,
        WorkExperience = 11,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1209",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 69,
        CompanyId = 1214,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 45,
        WorkExperience = 9,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1214",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 70,
        CompanyId = 1219,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.Exempt,
        Age = 36,
        WorkExperience = 9,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1219",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 71,
        CompanyId = 1220,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 30,
        WorkExperience = 9,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1220",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 72,
        CompanyId = 1230,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Preparation",
        PositionType = PositionType.BlueCollar,
        Age = 42,
        WorkExperience = 8,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1230",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 73,
        CompanyId = 1243,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.BlueCollar,
        Age = 45,
        WorkExperience = 7,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1243",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 74,
        CompanyId = 1256,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 32,
        WorkExperience = 7,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1256",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 75,
        CompanyId = 1259,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Preparation",
        PositionType = PositionType.BlueCollar,
        Age = 47,
        WorkExperience = 7,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1259",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 76,
        CompanyId = 1264,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Customer service",
        PositionType = PositionType.Exempt,
        Age = 52,
        WorkExperience = 6,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1264",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 77,
        CompanyId = 1275,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 41,
        WorkExperience = 6,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1275",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 78,
        CompanyId = 1279,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Logistics",
        PositionType = PositionType.WhiteCollar,
        Age = 47,
        WorkExperience = 6,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1279",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 79,
        CompanyId = 1280,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Dispatch",
        PositionType = PositionType.WhiteCollar,
        Age = 47,
        WorkExperience = 6,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1280",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 80,
        CompanyId = 1284,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Programming",
        PositionType = PositionType.WhiteCollar,
        Age = 34,
        WorkExperience = 6,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1284",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 81,
        CompanyId = 1291,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Planning & Strategy",
        PositionType = PositionType.WhiteCollar,
        Age = 33,
        WorkExperience = 5,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1291",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 82,
        CompanyId = 1294,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 25,
        WorkExperience = 5,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1294",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 83,
        CompanyId = 1301,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Stores",
        Line = "Stores",
        PositionType = PositionType.BlueCollar,
        Age = 30,
        WorkExperience = 5,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1301",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 84,
        CompanyId = 1307,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.BlueCollar,
        Age = 52,
        WorkExperience = 4,
        EducationLevel = EducationLevel.KV,
        RoleId = 2,
        Password = "1307",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 85,
        CompanyId = 1328,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Scrap management",
        PositionType = PositionType.BlueCollar,
        Age = 31,
        WorkExperience = 4,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1328",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 86,
        CompanyId = 1330,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Preparation",
        PositionType = PositionType.BlueCollar,
        Age = 28,
        WorkExperience = 4,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1330",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 87,
        CompanyId = 1340,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Customer service & Logistics",
        PositionType = PositionType.Exempt,
        Age = 44,
        WorkExperience = 3,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1340",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 88,
        CompanyId = 1342,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Chemical labaratory",
        PositionType = PositionType.BlueCollar,
        Age = 46,
        WorkExperience = 5,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1342",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 89,
        CompanyId = 1357,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Customer service",
        PositionType = PositionType.WhiteCollar,
        Age = 47,
        WorkExperience = 2,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1357",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 90,
        CompanyId = 1361,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Stores",
        Line = "Stores",
        PositionType = PositionType.BlueCollar,
        Age = 30,
        WorkExperience = 2,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1361",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 91,
        CompanyId = 1363,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Customer service & Logistics",
        Line = "Logistics",
        PositionType = PositionType.WhiteCollar,
        Age = 41,
        WorkExperience = 2,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1363",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 92,
        CompanyId = 1368,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Chemical labaratory",
        PositionType = PositionType.BlueCollar,
        Age = 47,
        WorkExperience = 1,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1368",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 93,
        CompanyId = 1370,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Labaratory control",
        PositionType = PositionType.BlueCollar,
        Age = 52,
        WorkExperience = 1,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1370",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 94,
        CompanyId = 1381,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Labaratory control",
        PositionType = PositionType.BlueCollar,
        Age = 24,
        WorkExperience = 1,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1381",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 95,
        CompanyId = 1394,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Quality control",
        Line = "Quality control",
        PositionType = PositionType.Exempt,
        Age = 30,
        WorkExperience = 0,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1394",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 96,
        CompanyId = 1401,
        Gender = Gender.Female,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Planning & Strategy",
        PositionType = PositionType.WhiteCollar,
        Age = 24,
        WorkExperience = 0,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1401",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 97,
        CompanyId = 1406,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Planning & Strategy",
        Line = "Preparation",
        PositionType = PositionType.BlueCollar,
        Age = 27,
        WorkExperience = 0,
        EducationLevel = EducationLevel.SSS,
        RoleId = 2,
        Password = "1406",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 98,
        CompanyId = 1058,
        Gender = Gender.Male,
        Sector = Sector.Sales,
        Department = "Sales",
        Line = "Sales",
        PositionType = PositionType.Exempt,
        Age = 55,
        WorkExperience = 27,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1058",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 99,
        CompanyId = 1145,
        Gender = Gender.Male,
        Sector = Sector.Sales,
        Department = "Sales",
        Line = "Sales",
        PositionType = PositionType.Exempt,
        Age = 52,
        WorkExperience = 25,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1145",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 100,
        CompanyId = 1211,
        Gender = Gender.Female,
        Sector = Sector.Sales,
        Department = "Sales",
        Line = "Sales",
        PositionType = PositionType.WhiteCollar,
        Age = 35,
        WorkExperience = 11,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1211",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 101,
        CompanyId = 1225,
        Gender = Gender.Female,
        Sector = Sector.Sales,
        Department = "Sales",
        Line = "Sales",
        PositionType = PositionType.Exempt,
        Age = 53,
        WorkExperience = 6,
        EducationLevel = EducationLevel.VSS,
        RoleId = 2,
        Password = "1225",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
            new User
    {
        Id = 102,
        CompanyId = 1250,
        Gender = Gender.Male,
        Sector = Sector.Sales,
        Department = "Sales",
        Line = "Sales",
        PositionType = PositionType.Exempt,
        Age = 40,
        WorkExperience = 17,
        EducationLevel = EducationLevel.MR,
        RoleId = 2,
        Password = "1250",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },


    // Role 1 - Admin
    new User
    {
        Id = 100,
        CompanyId = 99999,
        Gender = Gender.Male,
        Sector = Sector.Other,
        Department = "NoneDept",
        Line = "NoneDept",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 1,
        Password = "99999",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },

    // Role 3 - MCViewAll
    new User
    {
        Id = 101,
        CompanyId = 11184,
        Gender = Gender.Female,
        Sector = Sector.Other,
        Department = "NoneDept",
        Line = "NoneDept",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 3,
        Password = "11184",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 102,
        CompanyId = 11203,
        Gender = Gender.Female,
        Sector = Sector.Other,
        Department = "NoneDept",
        Line = "NoneDept",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 3,
        Password = "11203",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },

    // Role 4 - Sector Managers
    new User
    {
        Id = 103,
        CompanyId = 11060,
        Gender = Gender.Male,
        Sector = Sector.ProjectsProgressIT,
        Department = "ProjectsProgressIT",
        Line = "ProjectsProgressIT",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 4,
        Password = "11060",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 104,
        CompanyId = 11185,
        Gender = Gender.Female,
        Sector = Sector.Finance,
        Department = "Finance",
        Line = "Finance",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 4,
        Password = "11185",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },

    // Role 5 - Department Managers
    new User
    {
        Id = 105,
        CompanyId = 21069,
        Gender = Gender.Female,
        Sector = Sector.ProjectsProgressIT,
        Department = "High voltage",
        Line = "High voltage",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 5,
        Password = "21069",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 106,
        CompanyId = 21074,
        Gender = Gender.Male,
        Sector = Sector.SupplyChain,
        Department = "Stores",
        Line = "Stores",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 5,
        Password = "21074",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },

    // Role 6 - Line Managers
    new User
    {
        Id = 107,
        CompanyId = 31043,
        Gender = Gender.Male,
        Sector = Sector.Production,
        Department = "Coating Unit",
        Line = "Prepainting line",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 6,
        Password = "31043",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    },
    new User
    {
        Id = 108,
        CompanyId = 31052,
        Gender = Gender.Male,
        Sector = Sector.Production,
        Department = "Coating Unit",
        Line = "Tension Leveler",
        PositionType = PositionType.Other,
        Age = 1,
        WorkExperience = 1,
        EducationLevel = EducationLevel.Other,
        RoleId = 6,
        Password = "31052",
        IsActive = true,
        CreatedDate = DateTime.UtcNow
    }
);
            modelBuilder.Entity<QuestionForm>().HasData(
                new QuestionForm { Id = 1, Title = "Општо задоволство", Description = "Overall Satisfaction" },
                new QuestionForm { Id = 2, Title = "Обврска кон компанијата", Description = "Commitment to the Company" },
                new QuestionForm { Id = 3, Title = "Професионален развој", Description = "Professional Development" },
                new QuestionForm { Id = 4, Title = "Рамнотежа помеѓу работата и животот", Description = "Work-Life Balance" },
                new QuestionForm { Id = 5, Title = "Комуникација и соработка", Description = "Communication and Collaboration" },
                new QuestionForm { Id = 6, Title = "Лидерство", Description = "Leadership" },
                new QuestionForm { Id = 7, Title = "Организациска култура", Description = "Organizational Culture" },
                new QuestionForm { Id = 8, Title = "Работна средина", Description = "Work Environment" },
                new QuestionForm { Id = 9, Title = "Награди и признанија", Description = "Rewards and Recognition" },
                new QuestionForm { Id = 10, Title = "Иновации и промени", Description = "Innovation and Changes" },
                new QuestionForm { Id = 11, Title = "Конечна евалуација", Description = "Final Evaluation" },
                new QuestionForm { Id = 12, Title = "Отворени прашања", Description = "Open Questions" }
            );
            modelBuilder.Entity<Question>().HasData(
                // Form 1: Општо задоволство (Scale questions)
                new Question { Id = 1, Text = "Задоволен сум од мојата моментална работа", QuestionTypeId = 1, QuestionFormId = 1, UserId = 1 },
                new Question { Id = 2, Text = "Чувствувам дека мојата работа е ценета во рамките на компанијата", QuestionTypeId = 1, QuestionFormId = 1, UserId = 1 },
                new Question { Id = 3, Text = "Се чувствувам мотивиран да одам на работа секој ден", QuestionTypeId = 1, QuestionFormId = 1, UserId = 1 },
                new Question { Id = 40, Text = "Вашето задоволство", QuestionTypeId = 2, QuestionFormId = 1, UserId = 1 },

                // Form 2: Обврска кон компанијата (Scale questions)
                new Question { Id = 4, Text = "Се чувствувам горд што работам за оваа компанија", QuestionTypeId = 1, QuestionFormId = 2, UserId = 1 },
                new Question { Id = 5, Text = "Со задоволство ја препорачувам оваа компанија како работно место на пријателите и семејството", QuestionTypeId = 1, QuestionFormId = 2, UserId = 1 },
                new Question { Id = 6, Text = "Се гледам себеси како долгорочно работам во оваа компанија", QuestionTypeId = 1, QuestionFormId = 2, UserId = 1 },
                new Question { Id = 41, Text = "Вашата Обврска кон компанијата", QuestionTypeId = 2, QuestionFormId = 2, UserId = 1 },

                // Form 3: Професионален развој (Scale questions)
                new Question { Id = 7, Text = "Имам можности за професионален развој и напредување", QuestionTypeId = 1, QuestionFormId = 3, UserId = 1 },
                new Question { Id = 8, Text = "Добивам конструктивна повратна информација за мојата работа", QuestionTypeId = 1, QuestionFormId = 3, UserId = 1 },
                new Question { Id = 9, Text = "Компанијата обезбедува соодветна обука и ресурси за мојот развој", QuestionTypeId = 1, QuestionFormId = 3, UserId = 1 },
                new Question { Id = 42, Text = "Вашиот Професионален развој", QuestionTypeId = 2, QuestionFormId = 3, UserId = 1 },

                // Form 4: "Рамнотежа помеѓу работата и животот" (Scale questions)
                new Question { Id = 10, Text = "Компанијата поддржува здрава рамнотежа помеѓу работата и личниот живот", QuestionTypeId = 1, QuestionFormId = 4, UserId = 1 },
                new Question { Id = 11, Text = "Можам ефикасно да управувам со стресот поврзан со работата", QuestionTypeId = 1, QuestionFormId = 4, UserId = 1 },
                new Question { Id = 12, Text = "Мојот работен распоред ми овозможува да ги исполнувам моите лични обврски", QuestionTypeId = 1, QuestionFormId = 4, UserId = 1 },
                new Question { Id = 43, Text = "Вашата Рамнотежа помеѓу работата и животот", QuestionTypeId = 2, QuestionFormId = 4, UserId = 1 },

                // Form 5: "Комуникација и соработка" (Scale questions)
                new Question { Id = 13, Text = "Комуникацијата во мојот тим е ефикасна", QuestionTypeId = 1, QuestionFormId = 5, UserId = 1 },
                new Question { Id = 14, Text = "Се чувствувам удобно да ги искажувам моите идеи и мислења на работа", QuestionTypeId = 1, QuestionFormId = 5, UserId = 1 },
                new Question { Id = 15, Text = "Соработката помеѓу одделенијата е ефикасна", QuestionTypeId = 1, QuestionFormId = 5, UserId = 1 },
                new Question { Id = 44, Text = "Вашата Комуникација и соработка", QuestionTypeId = 2, QuestionFormId = 5, UserId = 1 },

                // Form 6: "Лидерство" (Scale questions)
                new Question { Id = 16, Text = "Му верувам на раководството на компанијата", QuestionTypeId = 1, QuestionFormId = 6, UserId = 1 },
                new Question { Id = 17, Text = "Мојот директен менаџер ме поддржува во остварувањето на моите цели", QuestionTypeId = 1, QuestionFormId = 6, UserId = 1 },
                new Question { Id = 18, Text = "Важните одлуки на компанијата се пренесуваат транспарентно", QuestionTypeId = 1, QuestionFormId = 6, UserId = 1 },
                new Question { Id = 45, Text = "Лидерство Општо", QuestionTypeId = 2, QuestionFormId = 6, UserId = 1 },

                // Form 7: "Организациска култура" (Scale questions)
                new Question { Id = 19, Text = "Вредностите на компанијата се усогласуваат со моите лични вредности", QuestionTypeId = 1, QuestionFormId = 7, UserId = 1 },
                new Question { Id = 20, Text = "Се чувствувам вклучено и почитувано на работа", QuestionTypeId = 1, QuestionFormId = 7, UserId = 1 },
                new Question { Id = 21, Text = "Компанијата промовира различност и инклузија", QuestionTypeId = 1, QuestionFormId = 7, UserId = 1 },
                new Question { Id = 46, Text = "Вашата Организациска култура ", QuestionTypeId = 2, QuestionFormId = 7, UserId = 1 },

                // Form 8: "Работна средина" (Scale questions)
                new Question { Id = 22, Text = "Ги имам сите ресурси потребни за ефикасно извршување на моите задачи", QuestionTypeId = 1, QuestionFormId = 8, UserId = 1 },
                new Question { Id = 23, Text = "Физичката работна средина е удобна и поволна за продуктивност", QuestionTypeId = 1, QuestionFormId = 8, UserId = 1 },
                new Question { Id = 24, Text = "Се чувствувам безбедно на работа", QuestionTypeId = 1, QuestionFormId = 8, UserId = 1 },
                new Question { Id = 47, Text = "Вашата Работна средина ", QuestionTypeId = 2, QuestionFormId = 8, UserId = 1 },

                // Form 9: "Награди и признанија" (Scale questions)
                new Question { Id = 25, Text = "Задоволен сум од мојот пакет компензации и бенефиции", QuestionTypeId = 1, QuestionFormId = 9, UserId = 1 },
                new Question { Id = 26, Text = "Моите напори и достигнувања се препознаени и ценети", QuestionTypeId = 1, QuestionFormId = 9, UserId = 1 },
                new Question { Id = 27, Text = "Постојат јасни можности за напредување во кариерата во рамките на компанијата", QuestionTypeId = 1, QuestionFormId = 9, UserId = 1 },
                new Question { Id = 48, Text = "Вашите Награди и признанија ", QuestionTypeId = 2, QuestionFormId = 9, UserId = 1 },

                // Form 10: "Иновации и промени" (Scale questions)
                new Question { Id = 28, Text = "Компанијата ги поттикнува иновациите и креативното размислување", QuestionTypeId = 1, QuestionFormId = 10, UserId = 1 },
                new Question { Id = 29, Text = "Подготвен сум да ги усвојам промените имплементирани во компанијата", QuestionTypeId = 1, QuestionFormId = 10, UserId = 1 },
                new Question { Id = 30, Text = "Идеите и предлозите на вработените се разгледуваат и се спроведуваат кога е соодветно", QuestionTypeId = 1, QuestionFormId = 10, UserId = 1 },
                new Question { Id = 49, Text = "Вашите Иновации и промени", QuestionTypeId = 2, QuestionFormId = 10, UserId = 1 },

                // Form 11: "Конечна евалуација" (Scale and text questions)
                new Question { Id = 31, Text = "Kолку е веројатно да ја препорачате оваа компанија како работно место на пријател или колега", QuestionTypeId = 1, QuestionFormId = 11, UserId = 1 },
                new Question { Id = 32, Text = "Како ја гледате вашата иднина во оваа компанија во следните 2-3 години?", QuestionTypeId = 2, QuestionFormId = 11, UserId = 1 },
                new Question { Id = 33, Text = "разно", QuestionTypeId = 2, QuestionFormId = 11, UserId = 1 },

                // Form 12: Отворени прашања (Text questions)
                new Question { Id = 34, Text = "Што најмногу ви се допаѓа на вашето сегашно работно место?", QuestionTypeId = 2, QuestionFormId = 12, UserId = 1 },
                new Question { Id = 35, Text = "Кои се најголемите предизвици со кои се соочувате на работа?", QuestionTypeId = 2, QuestionFormId = 12, UserId = 1 },
                new Question { Id = 36, Text = "Какви предлози имате за подобрување на работната средина или процесите на компанијата?", QuestionTypeId = 2, QuestionFormId = 12, UserId = 1 }
            );
        }
    }
}
